version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.10.0
    steps:
      - checkout
      - run:
          "yarn install"
      - run:
          "nvm install 7.0.0"
      - run:
          "nvm install 6.10.0"
    # For some reason phantomjs-prebuild is failing w/yarn, but npm installing works
      - run:
          "npm install phantomjs-prebuilt"
      # Switch to 7 and lint
      - run:
          "nvm use 7.0 && yarn lint:ci && yarn build && yarn test:node -- --maxWorkers=4"
      - run:
          "nvm use 7.0 && yarn test:web -- --maxWorkers=4 && yarn build:web -- --maxWorkers=4"
      # Switch to check on 4.3.2
      - run:
          "nvm use 6.10 && yarn build && yarn test:node -- --maxWorkers=4"
# ## Customize the test machine
# machine:
#   pre:
#     - mkdir ~/.yarn-cache
#
#   node:
#     version:
#       6.10
#
# ## Customize dependencies
# dependencies:
#   pre:
#     - curl -o- -L https://yarnpkg.com/install.sh | bash
#     - nvm install 7.0.0
#     - nvm install 6.10.0
#     # For some reason phantomjs-prebuild is failing w/yarn, but npm installing works
#     - npm install phantomjs-prebuilt
#
#   cache_directories:
#     - ~/.yarn-cache
#   override:
#     - yarn install




